main: WizardStaffMain
name: wizard_staff
version: 1.16
author: navy_master
commands:
  learnmagic:
    description: learn a magic
    aliases: lm
    permission: learnmagic.use
    usage: /<command> <playername> <magicname>
  playerhandbook:
    description: get the player's handbook
    aliases: phb
    usage: /<command>
  setplayerhandbook:
    description: set the player's handbook
    aliases: setphb
    usage: /<command>